---
title: "HW07"
author: "黃榆珮"
date: "2019年4月7日"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
rm(list=ls())
con = gzcon(url('http://www.systematicportfolio.com/sit.gz', 'rb'))
source(con)
close(con)
load.packages('quantmod')

data <- getSymbols('SPY', src = 'yahoo', from = '2000-01-01', to = '2018-12-31', auto.assign = F)
# buy and hold
signal <- rep(1, nrow(data))
buy.hold <- bt.simple(data, signal)
buy.hold$equity<-as.xts(buy.hold$equity)
head(buy.hold$equity)
tail(buy.hold$equity)
buy.hold$ret<-as.xts(buy.hold$ret)
head(buy.hold$ret)
# MA cross (moving average)
# Cl: get closing price
sma <- SMA(Cl(data), 200)
head(sma, 201)
#
signal <- ifelse(Cl(data) > sma, 1, 0) # if price large than moving mean, buy
head(signal, 201)
sma.cross <- bt.simple(data, signal)
names(sma.cross)
tail(sma.cross$equity)
#---------------------------------------------------------------------
# Create a chart showing the strategies perfromance in 2000:2009
dates <- '2000::2018'
buy.hold.equity <- buy.hold$equity[dates] / as.double(buy.hold$equity[dates][1])
sma.cross.equity <- sma.cross$equity[dates] / as.double(sma.cross$equity[dates][1])

# chartSeries() : Charting tool to create standard financial charts given a time series like object
chartSeries(buy.hold.equity, TA = c(addTA(sma.cross.equity, on=1, col='red')), 
            theme ='white', yrange = range(buy.hold.equity, sma.cross.equity) )
#------------------------------------------------------------------------
library(magrittr)
strategy.sma<-merge(buy.hold.equity, sma.cross.equity) %>% 
  set_colnames(c("BH", "SMA"))
head(strategy.sma,30)
tail(strategy.sma)
# plot using ggplot2 
library(ggplot2)
strategy.sma.df<-fortify(strategy.sma, melt=TRUE)
head(strategy.sma.df)
#
p<-ggplot(strategy.sma.df, aes(x = Index, y = Value))+
  geom_line(aes(color = Series), size = 0.5) +
  scale_x_date(date_labels = "%Y/%m")  # +
  #geom_hline(yintercept = c(1.0, 0.6)) # +  
  #geom_text(aes( 0, 0.6, label = 0.6, vjust = -1))

p
#******************************************************************    
load.packages('quantmod')
tickers <- spl('SPY')

data1 <- new.env() # data is a environment

getSymbols(tickers, src = 'yahoo', from = '2000-01-01', to = '2018-12-31', env = data1, auto.assign = T)
bt.prep(data1, align='keep.all')
names(data1)

head(data1$prices)
tail(data1$prices)
#*****************************************************************
data1$weight[] <- 1
buy.hold <- bt.run.share(data1, clean.signal=F, trade.summary = TRUE)
buy.hold <- bt.run(data1)
# MA Cross
# bt.apply function applies user given function to each symbol in the data environment
prices<-data1$prices
sma.1 <- bt.apply(data1, function(x) { SMA(Cl(x), 200) } ) 
head(sma.1, 201)
data1$weight[] <- NA # update weights matirx
data1$weight[] <- iif(prices >= sma.1, 1, 0)
sma.1.cross <- bt.run(data1, trade.summary=T)   
# 
plotbt.custom.report(sma.1.cross, buy.hold)
#
models<-list("SMA"= sma.1.cross, "BH" = buy.hold)
strategy.performance.snapshoot(sma.1.cross, T) 
strategy.performance.snapshoot(buy.hold, T) 
strategy.performance.snapshoot(models, T) 

etf4.all<-readRDS("etf4_xts_all")
head(etf4.all)
etf4.all.1<-etf4.all[complete.cases(etf4.all),]
head(etf4.all.1)
tail(etf4.all.1)

chartSeries(etf4.all.1, TA = c(addTA(sma.cross.equity, on=1, col='red')), 
            theme ='white', yrange = range(buy.hold.equity, sma.cross.equity) )
```